# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.12.0
_src_path: gh:radio-aktywne/template-meta
accountname: radio-aktywne
description: MinIO database template 🦩
reponame: template-database-minio
repourl: https://github.com/radio-aktywne/template-database-minio
templatename: minio
type: database
